### ISSUE TITLE
CSV output as a single array and traversing \KzykHys\CsvParser\CsvParser does not work

### ISSUE THREAD

**Issue by chadwick37** [kzykhys/PHPCsvParser#3]
Hi,
I'm trying to implement your parser. If I export a CSV from phpmyadmin the CSV is parsed fine with each row it's own array. However, I am using the Datatables jquery plugin and when I use their TableTools to export a CSV and then parse with your script it is all one array, not a separate array for each row. You can test by exporting from the table here: http://datatables.net/release-datatables/extras/TableTools/index.html

I have also tried your instructions for traversing \KzykHys\CsvParser\CsvParser because I will be importing large datasets; however, nothing is output when attempting to traverse. It just doesn't work no matter what CSV I test with. Thanks for your help.

Chad

**Comment by kzykhys** [comment]
Could you try again after `composer update`?
I found a mistake on installation guide.

``` json
{
    "require": {
        "kzykhys/php-csv-parser": ">=1.1.0"
    }
}
```

Thank you for reporting :smile:

**Comment by kzykhys** [comment]
Seems good after upgrade to 1.4.x

``` php
<?php
require __DIR__ . '/vendor/autoload.php';
$parser = \KzykHys\CsvParser\CsvParser::fromFile('TableTools example.csv');
var_dump($parser->parse());
```

```
array(59) {
  [0]=>
  array(5) {
    [0]=>
    string(16) "Rendering engine"
    [1]=>
    string(7) "Browser"
    [2]=>
    string(11) "Platform(s)"
    [3]=>
    string(14) "Engine version"
    [4]=>
    string(9) "CSS grade"
  }
  [1]=>
  array(5) {
    [0]=>
    string(5) "Gecko"
    [1]=>
    string(11) "Firefox 1.5"
    [2]=>
    string(16) "Win 98+ / OSX.2+"
    [3]=>
    string(3) "1.8"
    [4]=>
    string(1) "A"
  }
// .... snip ...
```

**Comment by chadwick37** [comment]
Thank you for responding so quickly. Works perfectly now.

**Comment by kzykhys** [comment]
Good to hear. Thank you.
