### ISSUE TITLE
Problem with line endings

### ISSUE THREAD

**Issue by chadwick37** [kzykhys/PHPCsvParser#4]
Hi,
I've successfully implemented PHPCsvParser and when I use it to upload a CSV I have no problems. I'm saving the CSV using Openoffice. However, whenever someone else uploads a CSV that was exported with Microsoft Excel the line endings are not recognized so it comes in as one long string. If I open the file using Openoffice there is no problem and if I re-save it then it will upload without a problem. Do you have any experience with this issue? I assume Excel is using a different line ending that the parser isn't recognizing, is there a way to test which line ending is being used so that it can be sent to the parser? Thanks for any help you can give.

**Comment by raphaelhuefner** [comment]
Did you use Microsoft Excel on Microsoft Windows or on Mac OS X?

Because by default, Excel uses different line endings for exporting CSV files, depending on the operating system.

Microsoft Excel on Windows --> CRLF
Microsoft Excel on OS X --> CR
Openoffice --> LF

**Comment by chadwick37** [comment]
I think I found the solution. Placing this in my code before running the parser seems to solve the issue:

ini_set("auto_detect_line_endings", "1");

**Comment by kzykhys** [comment]
@chadwick37 Thanks for reporting. I will add a note about "auto_detect_line_endings" on README at this time. (I will close this issue after some tests)

@raphaelhuefner Thanks for helping. I didn't know that Microsoft Excel on OS X is using CR by default.

**Comment by chadwick37** [comment]
It seems there are still issues with line endings. When importing a CSV created by Microsoft Excel on a Mac not all rows will import. On one test file only the first 2 rows of 44 rows will import. On another file 17 of 75 rows will import. If I parse the CSV string like this every row is imported: $file = str_getcsv($file, "\r");

I've looked through CsvParser.php and I'm not able to figure out why line endings with \r are not being handled.

**Comment by chadwick37** [comment]
Here is my solution, it would be nice if this was handled in the parser. Before giving the string to the parser I run it through this function:

<pre>
        public function normalize($string) {
            // Normalize line endings
            // Convert all line-endings to UNIX format
            $string = str_replace("\r\n", "\n", $string);
            $string = str_replace("\r", "\n", $string);
            // Don't allow out-of-control blank lines
            $string = preg_replace("/\n{2,}/", "\n\n", $string);
            
            return $string;
        }   
</pre>

**Comment by kzykhys** [comment]
Upgrading to 1.4.1 will solve this issue :)
